
name: Cypress Tests


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: secret
        env:
          CREDENTIALS: ${{ secrets.CYPRESS_ENV }}
        run: echo $CREDENTIALS > cypress.env.json

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install


      - name: Run Cypress tests
        run: npx cypress run --browser chrome || true
        env:
          CI: true
          

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports